<?php

return [
    'JENGA_USERNAME' => env('JENGA_USERNAME', '550294797X'),
    'JENGA_PASSWORD' => env('JENGA_PASSWORD', 'U9pG1tHCrzDR9PLXYrMZ3fwxtjAp2x0v2'),
    'JENGA_API_KEY' => env('JENGA_API_KEY', 'UWZQZFI4Q2xUbThiaWhUeUkweFd2x0v22x0v22x0v22x0v22x0v22x0v22x0v2=='),
    'JENGA_ENVIRONMENT' => env('JENGA_ENVIRONMENT_LIVE', true),// Set to false for sandbox testing

    'JENGA_PRIVATE_KEY' => env('JENGA_PRIVATE_KEY', storage_path() . 'private.pem'),
    'JENGA_BASE_ENDPOINT' => env('JENGA_BASE_ENDPOINT', 'https://uat.jengahq.io'),
    'JENGA_ACCOUNT_ID' => env('JENGA_ACCOUNT_ID', '5502947979X'),
    'JENGA_CURRENCY_DEFAULT' => env('JENGA_CURRENCY_DEFAULT', 'KES'),
    'JENGA_CALLBACK_DEFAULT' => env('JENGA_CALLBACK_DEFAULT', 'https://webhook.site/0a75a3f0-b545-4ce3-8c1f-926e7bded3df'),

    'JENGA_MERCHANT_NAME' => env('JENGA_MERCHANT_NAME', 'MERCHANT TEST SHOP'),
    'JENGA_MERCHANT_CODE' => env('JENGA_USERNAME'),
    'JENGA_MERCHANT_WEBSITE' => env('JENGA_MERCHANT_WEBSITE', 'https://uat.jengahq.io'),
    'JENGA_MERCHANT_OUTLET_CODE' => env('JENGA_MERCHANT_OUTLET_CODE', '0000000000'),
    'JENGA_EXTRA_DATA' => env('JENGA_EXTRA_DATA', 'NA'),
    'JENGA_CHECKOUT_LOGO_URL' => env('JENGA_CHECKOUT_LOGO_URL', 'NA'),
    'JENGA_CHECKOUT_BUTTON_CLASS' => env('JENGA_CHECKOUT_BUTTON_CLASS', 'btn btn-primary col-md-4'),
];
